services:

  serverbd:
    #Ignorado cuando se usa en modo swarm (swarm usa imágenes de un registry)
    build: ./basedatos/
    image: sebashh26/bd-clase-1
    # platform: linux/amd64
    # platform: linux/arm64
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=demobd
      - MYSQL_PASSWORD=toor
      - MYSQL_ROOT_HOST=%
    #volumes: 
    #   - ./data-db:/var/lib/mysql/
    # ports:
    #   - "3306"
    #Ignorado cuando se usa en swarm mode (usar restart_policy)
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password

  apipersona:
    build: api-persona/
    image: sebashh26/clase1-apipersona:latest
    environment: 
      - JAVA_OPTS=""
      - host=serverbd
      - port=3306
      - database=demobd
      - username=root
      - password=toor
    # depends_on:
    #   - serverbd
    #Si no especifico un puerto host, se creará uno aleatorio
    ports:
    - "8080"
    restart: on-failure
    #Sobreescribiendo el entrypoint del dockerfile
    # entrypoint: java -jar /workspace/app.jar

  apipreferencia:  
     build: api-preferencia/
     image: sebashh26/clase1-apipreferencia:latest
     environment: 
      - JAVA_OPTS=""
      - host=serverbd
      - port=3306
      - database=demobd
      - username=root
      - password=toor
      - url_apipersona=apipersona
      - port_apipersona=8080
     #depends_on: 
      #- mysql_server
      #- apipersona
     ports:
       - "8081"
     restart: on-failure
     entrypoint: java -jar /workspace/app.jar

# volumes:
#   my-data: